/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wetrade.common;

import org.junit.Test;
import static org.junit.Assert.*;

public class FabricProxyTest {
    @Test public void testSomeLibraryMethod() {
        FabricProxy classUnderTest = new FabricProxy();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
